osdf_system:
    libpath: /opt/app/osdf/libs
    osdf_ports:
        internal: 8699  # inside the Docker container, the app listens to this port
        external: 8698  # clients use this port on DockerHost
    osdf_ip_default: 0.0.0.0
#        # Important Note: At deployment time, we need to ensure the port mapping is done
#    ssl_context: ['./../etc/sniromanager.crt', './../etc/sniromanager.key']

osdf_temp:  # special configuration required for "workarounds" or testing
    local_policies:
        global_disabled: True
        local_placement_policies_enabled: True
        placement_policy_files_vcpe: # workaroud for policy platform glitches (or "work-arounds" for other components)
            - Affinity_vCPE_1.json
            - Capacity_vGMuxInfra.json
            - Capacity_vG_1.json
            - Distance_vGMuxInfra_1.json
            - Distance_vG_1.json
            - Min_Guarantee_vGMuxInfra_1.json
            - Placement_Optimization_1.json
            - QueryPolicy_vCPE.json
            - hpa_policy_vGMuxInfra_1.json
            - hpa_policy_vG_1.json
            - vnfPolicy_vG.json
            - vnfPolicy_vGMuxInfra.json
service_info:
    vCPE:
        vcpeHostName: requestParameters.vcpeHostName
        e2eVpnKey: requestParameters.e2eVpnKey

policy_info:
    placement:
        policy_fetch: by_scope
        policy_scope:
            default_scope: OSDF_R2
            scope_vcpe: OSDF_R2
            service_name: placementInfo.serviceModelInfo.modelName
        policy_subscriber: SubscriberPolicy
        subscriber_name: placementInfo.subscriberInfo.subscriberName
    default:  # if no explicit service related information is needed
        policy_fetch: by_name
        policy_scope: none
