osdf_system:
    libpath: /opt/app/osdf/libs
    sniro_ports:
        internal: 24699  # inside the Docker container, the app listens to this port
        external: 14699  # clients use this port on DockerHost
        # Important Note: At deployment time, we need to ensure the port mapping is done
    ssl_context: ['./../etc/sniromanager.crt', './../etc/sniromanager.key']

osdf_temp:  # hacks required for "workarounds" or testing
    local_policies:
        global_disabled: True
        local_placement_policies_enabled: True
        placement_policy_files_vcpe: # workaroud for policy platform glitches (or "work-arounds" for other components)
            - CloudAttributePolicy_vGMuxInfra_1.json
            - CloudAttributePolicy_vG_1.json
            - DistanceToLocationPolicy_vGMuxInfra_1.json
            - DistanceToLocationPolicy_vG_1.json
            - InventoryGroup_vGMuxInfra_1.json
            - InventoryGroup_vG_1.json
            - PlacementOptimizationPolicy.json
            - ResourceInstancePolicy_vG_1.json
            - VNFPolicy_vGMuxInfra_1.json
            - VNFPolicy_vG_1.json
            - ZonePolicy_vGMuxInfra_1.json
            - ZonePolicy_vG_1.json

service_info:
    vCPE:
        vcpeHostName: requestParameters.vcpeHostName
        e2eVpnKey: requestParameters.e2eVpnKey

policy_info:
    placement:
        policy_fetch: by_scope
        policy_scope:
            default_scope: OSDF_R2
            scope_vcpe: OSDF_R2
            service_name: placementInfo.serviceModelInfo.modelName
        policy_subscriber: SubscriberPolicy
        subscriber_name: placementInfo.subscriberInfo.subscriberName
    default:  # if no explicit service related information is needed
        policy_fetch: by_name
        policy_scope: none
