placementVersioningEnabled: True

# Placement API latest version numbers to be set in HTTP header
placementMajorVersion: "1"
placementMinorVersion: "0"
placementPatchVersion: "0"

# Placement API default version numbers to be set in HTTP header
placementDefaultMajorVersion: "1"
placementDefaultMinorVersion: "0"
placementDefaultPatchVersion: "0"

# Config for Conductor
conductorUrl: http://172.17.0.6:8091/v1/plans/
conductorPingWaitTime: 60  # seconds to wait before calling the conductor retry URL
conductorMaxRetries: 30  # if we don't get something in 30 minutes, give up
# versions to be set in HTTP header
conductorMinorVersion: 0

# Policy Platform -- requires Authorization
policyPlatformUrl: https://policy-xacml-pdp:6969/policy/pdpx/v1/decision # Policy Dev platform URL
# URL for policy model uploading
policyPlatformUrlModelUpload: https://policy.api.simpledemo.onap.org:8081/policy/api/v1/policytypes
pathPolicyModelUpload: ../../models/policy/placement/tosca_upload/

# Config for DMaaP
messageReaderHosts: NA
messageReaderTopic: NA

# Config for SDC
sdcUrl: NA
sdcONAPInstanceID: NA

# AAF Authentication config
is_aaf_enabled: False
aaf_cache_expiry_mins: 5
aaf_url: https://aaftest.simpledemo.onap.org:8095
aaf_user_roles:
  - '/placement:org.onap.oof.access|*|read ALL'
  - '/pci:org.onap.oof.access|*|read ALL'

# Secret Management Service from AAF
aaf_sms_url: https://aaf-sms.onap:10443
aaf_sms_timeout: 30
secret_domain: osdf
aaf_ca_certs: ssl_certs/aaf_root_ca.cer

# config db api
configDbUrl: http://config.db.url:8080
configDbGetCellListUrl: 'SDNCConfigDBAPI/getCellList'
configDbGetNbrListUrl: 'SDNCConfigDBAPI/getNbrList'

#aai api
aaiUrl: "https://aai.url:30233"
aaiGetLinksUrl: "/aai/v16/network/logical-links"
aaiServiceInstanceUrl : "/aai/v20/nodes/service-instances/service-instance/"
aaiGetControllersUrl: /aai/v19/external-system/esr-thirdparty-sdnc-list
controllerQueryUrl: /aai/v19/query?format=resource
aaiGetInterDomainLinksUrl: /aai/v19/network/logical-links?link-type=inter-domain&operational-status=up

#DES api
desUrl: http://des.url:9000
desApiPath: /datalake/v1/exposure/
desHeaders:
  Accept: application/json
  Content-Type: application/json
desUsername:
desPassword:

pciHMSUsername: test
pciHMSPassword: passwd

#key
#appkey: os35@rrtky400fdntc#001t5

#consulconfig
consulHost: '127.0.0.1'
consulPort: 8500
consulScheme: 'http'
consulVerify: True
consulCert: None
activateConsulConfig: False
