---
domain: osdf
secrets:
- name: so
  values:
    UserName: ''
    Password: ''
- name: conductor
  values:
    UserName: admin1
    Password: plan.15
- name: policy_platform
  values:
    UserName: testpdp
    Password: alpha123
- name: policy_client
  values:
    UserName: python
    Password: test
- name: dmaap
  values:
    UserName: NA
    Password: NA
- name: sdc
  values:
    UserName: NA
    Password: NA
- name: osdfPlacement
  values:
    UserName: test
    Password: testpwd
- name: osdfPlacementSO
  values:
    UserName: so_test
    Password: so_testpwd
- name: osdfPlacementVFC
  values:
    UserName: vfc_test
    Password: vfc_testpwd
- name: osdfCMScheduler
  values:
    UserName: test1
    Password: test_pwd1
